### ISSUE TITLE
Chapter 21 In-class

### ISSUE THREAD

**Issue by tyler-singkofer** [UNWSP-Android/nfro1land-BeatBox#6]
Complete all coding changes described in the chapter. When done, commit and sync your changes referencing this issue number. Use the format "Fixes #issue_number" to automatically close out the issue (this will happen once you merge your changes back to master) and mark your assignment as complete.

**Comment by nfro1land** [comment]
I forgot to add "fixes #6" to the title of the commit so the title of the commit for this issue is just "Fixes" in the chapter 21 branch.
